name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          sudo docker build -t myimage .
          sudo docker save -o myimage.tar myimage

        # 存储到 artifacts，以便在后续的步骤中使用
        - name: Save Docker Image
          uses: actions/upload-artifact@v2
          with:
            name: myimage
            path: myimage.tar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载保存的 Docker Image
        uses: actions/download-artifact@v2
        with:
          name: myimage
          path: /tmp

      - name: 加载 Docker Image
        run: |
          sudo docker load -i /tmp/myimage.tar

      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
          ARGS: '-avzr'
          REMOTE_HOST: '124.221.172.120'
          REMOTE_USER: 'root'
          SCRIPT_BEFORE: |
            docker run -p 8828:80 myimage
