name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-frontend-app .

      - name: Run Docker Container
        run: docker run -p 8828:80 --name xj22-nginx -v /xjdata2/nginx/html:/usr/share/nginx/html -v /xjdata2/nginx/logs:/var/log/nginx -v /xjdata2/nginx/conf:/etc/nginx/conf.d -v /xjdata2/nginx/cert:/etc/nginx/cert -d my-frontend-app
