name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        uses: actions/checkout@v4

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: sudo docker build -t nginx:latest .

      # 构建 Docker 镜像
      - name: Copy dist from Docker Container
        run: sudo docker cp $(sudo docker create nginx:latest):/app/dist ./dist

      # 发布到腾讯云
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@main
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: 'dist/*'
          # 服务器ip
          REMOTE_HOST: '49.235.118.67'
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/xjdata2/nginx/html'
          # 测试ssh连接
          SCRIPT_BEFORE: |
            docker stop xj22-nginx || true
            docker rm xj22-nginx || true
            docker run -p 8828:80 --name xj22-nginx -v /xjdata2/nginx/html:/usr/share/nginx/html -v /xjdata2/nginx/conf:/etc/nginx/conf.d -d nginx:latest
            sleep 5  # 等待 5 秒以确保容器已经正常运行
            docker logs xj22-nginx  # 打印容器日志
