name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myimage .
          docker save -o /tmp/myimage.tar myimage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 上传 Docker Image 到远程服务器
        run: scp -o StrictHostKeyChecking=no -i ${{ secrets.P_KEY }} /tmp/myimage.tar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/tmp/myimage.tar

      - name: 在远程服务器加载 Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.P_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo docker load -i /tmp/myimage.tar"

      - name: 发布到腾讯云
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.P_KEY }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "sudo docker run -p 8828:80 myimage:latest"
