name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-frontend-app .

      - name: Run Docker Container
        run: |
          docker stop xj22-nginx || true
          docker rm xj22-nginx || true
          docker run -p 8828:80 --name xj22-nginx -d my-frontend-app
