name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 获取代码
      - name: 迁出代码
        uses: actions/checkout@v4

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: sudo docker build -t myimage .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # 发布到腾讯云
      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@main
        with:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
          # SCP参数
          ARGS: '-avzr'
          # 服务器ip
          REMOTE_HOST: '124.221.172.120'
          # 用户
          REMOTE_USER: 'root'
          # 测试ssh连接
          SCRIPT_BEFORE: |
            docker run -p 8828:80 myimage
