name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t xj_image:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push xjane/xj_image:latest

      - name: SSH into server and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: 124.221.172.120
          username: root
          key: ${{ secrets.PRIVATEKEY }}
          port: 8828
          script: |
            docker pull xjane/xj_image:latest
            docker run -p 8828:80 --name xj22-nginx -d xj_image:latest
